### ISSUE TITLE
Uncaught exception 'JMS\Serializer\Exception\RuntimeException' 

### ISSUE THREAD

**Issue by leifnel** [dbojdo/gls-tracking#2]
> Fatal error: Uncaught exception 'JMS\Serializer\Exception\RuntimeException' with message 'Invalid data "Customer's own reference number"(string), expected "Webit\GlsTracking\Model\CustomerReference".' in .../vendor/webit/soap-api/src/Hydrator/HydratorSerializerBased.php on line 79

The json is fine, i can do json_encode(json_decode($json)) at line 79.

` "CustomerReference": {
        "ReferenceType": "Customer_s own reference number",
        "ReferenceValue": "294848"
    },`

I have found this much:

When hydrating a structure like exitCode, visitProperty is called recursively twice, with the "branch"
`"ExitCode": {
        "ErrorCode": 0,
        "ErrorDscr": "OK"
    }` as $data, 
first looking for ErrorCode, then for ErrorDscr.

But when hydrating CustomerReference, visitProperty is NOT called with the branch 
`   "CustomerReference": {
        "ReferenceType": "Customers own reference number",
        "ReferenceValue": "294848"
    },
`
but with the string  `Customer_s own reference number`
when looking for ReferenceType

I have compared ExitCode.php with CustomerReference.php, and I can not see any difference in the structure which could cause why ExitCode works and CustomerReference doesn't.

**Comment by leifnel** [comment]
Ahh, got it.

in TuDetailsResponse.php
`     * @JMS\Type("ArrayCollection<Webit\GlsTracking\Model\CustomerReference>")
`
This expects the CustomerReference to be an array of references, i.e. there can be multiple references, just as there can be multiple events in the History.

But (at least in my Danish experience, it is not an array, so changing that line to
` * @JMS\Type("Webit\GlsTracking\Model\CustomerReference")`
removes the error.

I'm not that into JMS etc to make it robust to handle if there is only one reference or multiple references.

**Comment by dbojdo** [comment]
@leifnel fixed in the version 1.0.0
